# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class Test5():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_5(self):
        # Test name: 5
        # Step # | name | target | value | comment
        # 1 | open | https://www.thsrc.com.tw/ |  |
        self.driver.get("https://www.thsrc.com.tw/")
        # 2 | setWindowSize | 851x852 |  |
        self.driver.set_window_size(851, 852)
        # 3 | mouseOver | css=.slick-current .pic-l |  |
        element = self.driver.find_element(
            By.CSS_SELECTOR, ".slick-current .pic-l")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        # 4 | mouseOut | css=.slick-current .pic-l |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element_with_offset(element, 0, 0).perform()
        # 5 | click | linkText=時刻表與票價查詢 |  | 點擊乘車資訊查詢
        self.driver.find_element(By.LINK_TEXT, "時刻表與票價").click()
        # 6 | click | id=select_location01 |  |
        self.driver.find_element(By.ID, "select_location01").click()
        # 7 | select | id=select_location01 | label=台北 | 點擊起程站台北
        dropdown = self.driver.find_element(By.ID, "select_location01")
        dropdown.find_element(By.XPATH, "//option[. = '台北']").click()
        # 8 | click | id=select_location02 |  |
        self.driver.find_element(By.ID, "select_location02").click()
        # 9 | select | id=select_location02 | label=台南 | 點擊到達站台南
        dropdown = self.driver.find_element(By.ID, "select_location02")
        dropdown.find_element(By.XPATH, "//option[. = '台南']").click()
        # 10 | click | id=typesofticket |  | 點擊選單
        self.driver.find_element(By.ID, "typesofticket").click()
        # 11 | click | id=typesofticket |  | 點擊單程
        self.driver.find_element(By.ID, "typesofticket").click()
        # 12 | select | id=typesofticket | label=單程 |
        dropdown = self.driver.find_element(By.ID, "typesofticket")
        dropdown.find_element(By.XPATH, "//option[. = '單程']").click()
        # 13 | click | id=typesofticket |  | 點擊去回程
        self.driver.find_element(By.ID, "typesofticket").click()
        # 14 | select | id=typesofticket | label=去回程 |
        dropdown = self.driver.find_element(By.ID, "typesofticket")
        dropdown.find_element(By.XPATH, "//option[. = '去回程']").click()
        # 15 | click | css=.filter-option-inner-inner |  |
        self.driver.find_element(
            By.CSS_SELECTOR, ".filter-option-inner-inner").click()
        # 16 | click | linkText=早鳥 |  |
        self.driver.find_element(By.LINK_TEXT, "早鳥").click()
        # 17 | addSelection | id=offer | label=早鳥 | 點擊早鳥
        dropdown = self.driver.find_element(By.ID, "offer")
        dropdown.find_element(By.XPATH, "//option[. = '早鳥']").click()
        # 18 | removeSelection | id=offer | label=校外教學 |
        dropdown = self.driver.find_element(By.ID, "offer")
        dropdown.find_element(By.XPATH, "//option[. = '校外教學']").click()
        # 19 | removeSelection | id=offer | label=大學生 |
        dropdown = self.driver.find_element(By.ID, "offer")
        dropdown.find_element(By.XPATH, "//option[. = '大學生']").click()
        # 20 | removeSelection | id=offer | label=20人團體 |
        dropdown = self.driver.find_element(By.ID, "offer")
        dropdown.find_element(By.XPATH, "//option[. = '20人團體']").click()
        # 21 | click | linkText=早鳥 |  | 再點擊早鳥
        self.driver.find_element(By.LINK_TEXT, "早鳥").click()
        # 22 | removeSelection | id=offer | label=早鳥 |
        dropdown = self.driver.find_element(By.ID, "offer")
        dropdown.find_element(By.XPATH, "//option[. = '早鳥']").click()
        # 23 | click | linkText=校外教學 |  | 點擊校外教學
        self.driver.find_element(By.LINK_TEXT, "校外教學").click()
        # 24 | addSelection | id=offer | label=校外教學 |
        dropdown = self.driver.find_element(By.ID, "offer")
        dropdown.find_element(By.XPATH, "//option[. = '校外教學']").click()
        # 25 | click | linkText=校外教學 |  | 再點擊校外教學
        self.driver.find_element(By.LINK_TEXT, "校外教學").click()
        # 26 | removeSelection | id=offer | label=校外教學 |
        dropdown = self.driver.find_element(By.ID, "offer")
        dropdown.find_element(By.XPATH, "//option[. = '校外教學']").click()
        # 27 | click | id=Departdate03 |  | 點擊去程日期
        self.driver.find_element(By.ID, "Departdate03").click()
        # 28 | click | css=tr:nth-child(3) > .day:nth-child(4) |  | 點擊日期
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(3) > .day:nth-child(4)").click()
        # 29 | click | id=outWardTime |  | 點擊時間
        self.driver.find_element(By.ID, "outWardTime").click()
        # 30 | click | css=td:nth-child(1) .fa-chevron-up |  | 小時增加
        self.driver.find_element(
            By.CSS_SELECTOR, "td:nth-child(1) .fa-chevron-up").click()
        # 31 | click | css=td:nth-child(1) .fa-chevron-down |  | 小時減少
        self.driver.find_element(
            By.CSS_SELECTOR, "td:nth-child(1) .fa-chevron-down").click()
        # 32 | click | css=td:nth-child(3) .fa-chevron-up |  | 增加三十分鐘
        self.driver.find_element(
            By.CSS_SELECTOR, "td:nth-child(3) .fa-chevron-up").click()
        # 33 | click | css=td:nth-child(3) .fa-chevron-down |  | 減少三十分鐘
        self.driver.find_element(
            By.CSS_SELECTOR, "td:nth-child(3) .fa-chevron-down").click()
        # 34 | click | id=start-search |  | 查詢
        self.driver.find_element(By.ID, "start-search").click()
